stages:
  - build

build:
  stage: build
  script:
    - mkdir -p $HOME/golang # for GOROOT (contains the Go binary & core packages)
    - mkdir -p $HOME/gopath # for GOPATH (contains code and external packages)
    - curl https://storage.googleapis.com/golang/go1.7.linux-amd64.tar.gz 2>/dev/null > go1.7.linux-amd64.tar.gz
    - tar -C $HOME/golang -xzf go1.7.linux-amd64.tar.gz
    - GOROOT=$HOME/golang/go
    - GOPATH=$HOME/gopath
    
    - mkdir -p $GOPATH/src/github.com/danielstutzman
    - rm -rf $GOPATH/src/github.com/danielstutzman/todomvc-backend-go
    - cp -R $PWD $GOPATH/src/github.com/danielstutzman
    - cd $GOPATH/src/github.com/danielstutzman/todomvc-backend-go
    - PATH=$PATH:$GOROOT/bin GOROOT=$GOROOT GOPATH=$GOPATH make vet
    - PATH=$PATH:$GOROOT/bin GOROOT=$GOROOT GOPATH=$GOPATH make coverage
